### PR TITLE
Screen switch

### PR DESCRIPTION
**Pull request by barbican-youth**
Option -s which opens a screen session using the line "screen /dev/serial0 9600"

### CODE REVIEW

**Comment by barbican-youth** [comment]
.

**Comment by larsbrinkhoff** [comment]
Thank you.  Did you really mean to submit this as a pull request?  There are changes in there that seem to only apply to your own fork.

**Comment by larsbrinkhoff** [comment]
As for the `-s` switch, I can see it's a useful addition.  I would like to suggest a generalization: the ability to send any user-specified string to the child process.

**Comment by barbican-youth** [comment]
@larsbrinkhoff My mistake, I didn't intend to merge this into the base repo. I went ahead and separated my fork so I can maintain my own repo. You are correct that the changes are specific to my use case.

Regarding the -s switch, the way I implemented it was by passing an ASCII string to the "send_character" function. I wonder if there is a more efficient way to do this? Perhaps there is already something in the code that can covert text to ASCII?

**Comment by larsbrinkhoff** [comment]
I don't think there is any ready to use text to ASCII function, but it would be trivial to make one iterating over characters in a char * input.

**Pull request closed without merging**
