### PR TITLE
3D model

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Add information about @kidmirage's 3D printed model.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
https://github.com/kidmirage/2-3-Scale-VT100-Terminal-Reproduction

https://www.instructables.com/23-Scale-VT100-Terminal-Reproduction/

**Comment by larsbrinkhoff** [comment]
My progress so far.

**Comment by felias-fogg** [comment]
I used the 3D model in order to build a VT100 replica, and with the simulator it looks almost real. I added a PiDP-11 amd use it now as display for showing the current state of my solar power system. 
IMG_1370

The most difficult thing was to write a K&R-C-program for querying my inverter.

**Comment by larsbrinkhoff** [comment]
That looks great, @felias-fogg!  May I post your photo online?

**Comment by larsbrinkhoff** [comment]
I put epoxy putty in the cracks and filed it down.  They I sprayed several layers of filler.

**Comment by felias-fogg** [comment]
Hi Lars,

sure!

Best,
Bernhard

**Comment by larsbrinkhoff** [comment]
Thank you!  Say, have you used PDP-10 computers in your career?  Maybe this: https://github.com/PDP-10/hamburg-pascal

**Comment by felias-fogg** [comment]
Yes, indeed! See, e.g.:  https://gki.informatik.uni-freiburg.de/papers/nebel-pretschner-tr-76.pdf

Von meinem iPad gesendet

Am 16.11.2023 um 17:32 schrieb Lars Brinkhoff ***@***.***

>:
Thank you!  Say, have you used PDP-10 computers in your career?  Maybe this: https://github.com/PDP-10/hamburg-pascal

**Comment by larsbrinkhoff** [comment]
Thanks!  I copied the PDF and another one I found to the repository.

**Pull request merged**
