### PR TITLE
Scanline, CRT shader

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Write an OpenGL shader for a fancier display appearance.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
https://learnopengl.com/Advanced-Lighting/Bloom

**Comment by larsbrinkhoff** [comment]
https://github.com/Kobe46/Shaderlay/blob/master/shaders/crt-pi-curvature-vertical.glsl

**Comment by larsbrinkhoff** [comment]
This was slammed as being too glowy.
glow

**Comment by larsbrinkhoff** [comment]
Toned it down a bit and adjusted for a display brightness around 75%  
This was rendered at high resolution in full screen mode.
glow2

**Comment by larsbrinkhoff** [comment]
Glitch pictures are fun too.
curve

**Comment by larsbrinkhoff** [comment]
zork

**Comment by larsbrinkhoff** [comment]
set-upa
set-upb
vt100-top

**Comment by kidmirage** [comment]
I'm loving the CRT curvature look!

**Comment by larsbrinkhoff** [comment]
The 9x9 Gaussian blur for a soft glow around the text is too slow.  Rather than waiting to implement a faster algorithm, I'll drop that and merge this now.

**Pull request merged**
